### ISSUE TITLE
Can you provide the address of the paper?

### ISSUE THREAD

**Issue by Changheng-Li** [yingtaoluo/STGCN-POI-Recommendation#2]

**Comment by yingtaoluo** [comment]
Thank you for your interest. Our paper is currently under review of a conference. To follow the double blind review policy, we do not link our paper to this repository nor provide any more information on Github. After acceptance, we shall release the dataset and the paper immediately. :}

**Comment by yingtaoluo** [comment]
The rebuttal day is Dec 2, 2020. We would not publish our paper on ARXIV or elsewhere prior to this day. If you intend to publish your paper before this day, you do not need to cite our paper. :}

**Comment by yingtaoluo** [comment]
Update! Our paper (STAN: Spatial-Temporal-Attention-Network-for-Next-Location-Recommendation) is accepted to the Web conference 2021. (Repository URL is https://github.com/yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation, https://arxiv.org/pdf/2102.04095.pdf)
